### ISSUE TITLE
Add config scopes

### ISSUE THREAD

**Issue by jlorieau** [jlorieau/geomancy#28]
Add config namespace scopes, which are filled in by checks. These can then be cached and used by programs to access configuration values.

**Comment by jlorieau** [comment]
Add a ``dest`` flag for populating configuration with the parsed values. For example
```yaml
checkUsername:
    desc: Get the current username
    dest: $ENV.user.username
```
