### ISSUE TITLE
Implement check rememdies

### ISSUE THREAD

**Issue by jlorieau** [jlorieau/geomancy#37]
Implement remedies in checks so that suggestions can be made for failed checks.

Examples 1: A url for missing dependencies
```yaml
Python:
  desc: Python interpreter
  url: https://www.python.org
  checkExec: python3 >= 3.11
```
Example 2: A remedy field
```yaml
S3TemplateBucket:
  checkS3: myproject-cfn-templates
  remedy:
    missing: Create bucket on the AWS console at https://aws.amazon.com/console/
    forbidden: Ask the bucket owner to give you access to the bucket
```
