### ISSUE TITLE
Parentheses in regexes

### ISSUE THREAD

**Issue by jlorieau** [jlorieau/geomancy#48]
The following code:

```yaml
CheckEnvironment:
    checkEnv: $ENV
    regex: (local|dev|prod)
```

raises and exception

```
AssertionError: The 'failed (does not match regex '(local|dev|prod)')' status should match the following regular expression: 're.compile('^(passed|failed|pending)( \\([^)\\n]+\\))?$')'
```
